---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.service.name }}
  labels:
    run: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    defacementComponent: {{ .Values.podName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.podName }}
  labels:
    defacementComponent: {{ .Values.podName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      defacementComponent: {{ .Values.podName }}
  template:
    metadata:
      labels:
        defacementComponent: {{ .Values.podName }}
    spec:
      containers:
        - image: {{ .Values.image }}
          name: {{ .Values.podName }}
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - redis-cli ping
            initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}